First pass edits + some open questions that need to be answered (mark…
katyhuff/2017-collaborative-siip pull request #1
Opened 2017-04-30 19:51 UTC by davis68

…ed with %Q).

2017-05-01 20:12 UTC, katyhuff requested changes
Thanks @davis68 !! I like lots of this, but not all. Given you have no more time this afternoon,  I'm going to pull it and fix the things I made comments on. Of most importance is that SWC specifically has struggled, and that's what I was trying to bring up. I'm not the first (this was in the lessons learned paper as well as greg's scipy keynote). I will add some text about what has worked within software carpentry, to your point, but I'm not going to name it a complete success. https://www.youtube.com/watch?v=1e26rp6qPbA#t=28m50s . And no, I'm not the lead instructor that he quotes.

2017-05-01 20:12 UTC, katyhuff commented on siip.tex
> +                  University of Illinois at Urbana--Champaign
This makes it too long for our names to both be on the top. That's why I left out the "at". :(

2017-05-01 20:12 UTC, katyhuff commented on siip.tex
> +          challenges, including instructor inertia, an unclear process for collaboration,
I like 'instructor inertia'

2017-05-01 20:12 UTC, katyhuff commented on siip.tex
> +          \textbf{Given our experience with successsful collaborative curriculum development
what experience with success has been met? I'm not sure what you're referring to.

2017-05-01 20:12 UTC, katyhuff commented on siip.tex
> +          Most notable among successful efforts is Software Carpentry (a program
Decidedly not. One of the key lessons learned from software carpentry is that it's failed to get as much collaboration as we expected. We had to force it at every step. See: lessons learned paper and Greg's scipy keynote, both cited here. Software carpentry faced challenges with this, that's what I'm saying here.

2017-05-01 20:12 UTC, katyhuff commented on siip.tex
> +          % TODO:  comment on how SWC has successfully surmounted the other challenges noted above
by forcing all new instructors to make arbitrary and likely-to-be-rejected PRs to become instructors? I'm not sure this qualifies as  successful surmounting. Anyway, Greg certainly doesn't think so.

2017-05-01 20:12 UTC, katyhuff commented on siip.tex
> +          introductory CS1 courses like CS101).
What does CS1 mean?

2017-05-01 20:12 UTC, katyhuff commented on siip.tex
> +          graph describing dependencies among lessons. Additionally, concrete logistics
Ideally this graph should have a single direction and there should be no cycles. Have I made some CS faux-pas here?

2017-05-01 20:12 UTC, katyhuff commented on siip.tex
> +          development assignments; decisions to adopt specific raw formats
I don't think semicolons are intended to break sentences in this way. Each side should be a full independent clause.

2017-05-01 20:12 UTC, katyhuff commented on siip.tex
> +          % TODO: what of Sp18?
Sp18 is before the second workshop. Thus, still part of the interim period.  I don't understand this question.

2017-05-01 20:12 UTC, katyhuff commented on siip.tex
> +          colleagues previously primarily connected by research
great rephrasing.

2017-05-01 20:42 UTC, merged

2017-05-01 20:42 UTC, katyhuff commented
![bitmoji](https://render.bitstrips.com/v2/cpanel/7834193-116454032_15-s1-v1.png?transparent=1&palette=1&width=246)

Thanks @davis68 !!

2017-05-02 14:57 UTC, davis68 commented on siip.tex
> +          introductory CS1 courses like CS101).
CS1 is the standard CS education term for any first college-level programming class (since listings can look quite different).  Since this proposal is internal to UIUC, it's probably superfluous.

2017-05-02 14:57 UTC, davis68 commented on siip.tex
> +          graph describing dependencies among lessons. Additionally, concrete logistics
No, it's precise, I was just suggesting simplifying the text.

2017-05-02 14:58 UTC, davis68 commented on siip.tex
> +          development assignments; decisions to adopt specific raw formats
Use it when there are commas in the subsidiary clauses in order to distinguish the relative level of division.  The commas here are already parenthesized though.

2017-05-02 14:59 UTC, davis68 commented on siip.tex
> +          % TODO: what of Sp18?
Question was related to what the intention of the interim period is—if there will be more structure to gathering lessons learned prior to the second workshop.  (I imagine there will be conversations, so we don't need anything formal.)